/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class HeartActor extends Actor {
  /** @override */
  prepareData() {
    // Prepare data for the actor. Calling the super version of this executes
    // the following, in order: data reset (to clear active effects),
    // prepareBaseData(), prepareEmbeddedDocuments() (including active effects),
    // prepareDerivedData().
    super.prepareData();
  }

  /** @override */
  prepareBaseData() {
    // Data modifications in this step occur before processing embedded
    // documents or derived data.
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    if (this.type === "character") {
      this.itemTypes.class.forEach(this.prepareDerivedClassData.bind(this));
      this.itemTypes.calling.forEach(this.prepareDerivedCallingData.bind(this));
    }
  }

  prepareDerivedClassData(cls) {
    const domain = cls.system.domain;
    const skill = cls.system.skill;

    let overrides = this.system.overrides ?? {};

    // Add one level of mastery to all domains & skills associated with a class.
    overrides = [
      `system.skills.${skill}.value`,
      `system.domains.${domain}.value`,
    ].reduce((output, route) => {
      const changes = ActiveEffect.prototype.apply(this, {
        key: route,
        value: 1,
        mode: CONST.ACTIVE_EFFECT_MODES.ADD,
      });
      Object.assign(output, changes);
      return output;
    }, overrides);

    Object.assign(this.overrides, foundry.utils.expandObject(overrides));

    // just set the item
    cls.itemTypes.equipment.forEach((equipment) => {
      if (equipment.flags.heart.equipment_group === "core") {
        this.items.set(equipment._id, equipment, { modifySource: false });
      }
    });

    cls.itemTypes.ability.forEach((ability) => {
      if (ability.system.type === "core") {
        this.items.set(ability._id, ability, { modifySource: false });
      }
    });
  }

  prepareDerivedCallingData(calling) {
    calling.itemTypes.equipment.forEach((equipment) => {
      if (equipment.flags.heart.equipment_group === "core") {
        this.items.set(equipment._id, equipment, { modifySource: false });
      }
    });
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return {
      ...super.getRollData(),
      ...(this.system.getRollData?.() ?? null),
      actor: this.id,
    };
  }

  /**
   * Convert the actor document to a plain object.
   *
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   *
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = { ...this };

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

  async updateStress(resistance, value) {
    if (value > this.system.total_stress) {
      return await this.update({
        [`system.resistances.${resistance}.value`]:
          this.system.resistances[resistance].value + value,
      });
    }

    if (value <= 6) {
      return await this.update({
        [`system.resistances.${resistance}.value`]: 0,
        "system.pending_fallouts.minor": this.system.pending_fallouts.minor + 1,
      });
    } else {
      return await this.update({
        [`system.resistances.${resistance}.value`]: 0,
        "system.pending_fallouts.major": this.system.pending_fallouts.major + 1,
      });
    }
  }
}
