import migrations from "../data/migrations/actor-migrations.mjs";

/**
 * Extend the base Actor document by defining a custom roll data structure which is ideal for the Simple system.
 * @extends {Actor}
 */
export class HeartActor extends Actor {
  static migrateData(source) {
    return super.migrateData(
      Object.entries(migrations)
        .filter(([version, _]) => {
          return foundry.utils.isNewerVersion(
            version,
            source._stats?.systemVersion ?? "0"
          );
        })
        .reduce((source, [_, migrator]) => {
          const out = migrator(source);
          Object.assign(source, out);
          return source;
        }, source)
    );
  }

  /**
   * @override
   * Augment the actor source data with additional dynamic data that isn't
   * handled by the actor's DataModel. Data calculated in this step should be
   * available both inside and outside of character sheets (such as if an actor
   * is queried and has a roll executed directly from it).
   */
  prepareDerivedData() {
    if (this.type === "character") {
      this.itemTypes.class.forEach(this.prepareDerivedClassData.bind(this));
      this.itemTypes.calling.forEach(this.prepareDerivedCallingData.bind(this));
    }

    const active_items = this.getActiveItems();
    active_items.forEach(item => {
      this.items.set(item._id, item, { modifySource: false });
    })
  }

  prepareDerivedClassData(cls) {
    const domain = cls.system.domain;
    const skill = cls.system.skill;

    let overrides = this.system.overrides ?? {};

    Object.assign(this.overrides, foundry.utils.expandObject(overrides));

  }

  prepareDerivedCallingData(calling) {
    calling.itemTypes.equipment.forEach((equipment) => {
      if (equipment.flags.heart.equipment_group === "core") {
        this.items.set(equipment._id, equipment, { modifySource: false });
      }
    });
  }

  /**
   *
   * @override
   * Augment the actor's default getRollData() method by appending the data object
   * generated by the its DataModel's getRollData(), or null. This polymorphic
   * approach is useful when you have actors & items that share a parent Document,
   * but have slightly different data preparation needs.
   */
  getRollData() {
    return {
      ...super.getRollData(),
      ...(this.system.getRollData?.() ?? null),
      actor: this.id,
    };
  }

  /**
   * Convert the actor document to a plain object.
   *
   * The built in `toObject()` method will ignore derived data when using Data Models.
   * This additional method will instead use the spread operator to return a simplified
   * version of the data.
   *
   * @returns {object} Plain object either via deepClone or the spread operator.
   */
  toPlainObject() {
    const result = { ...this };

    // Simplify system data.
    result.system = this.system.toPlainObject();

    // Add items.
    result.items = this.items?.size > 0 ? this.items.contents : [];

    // Add effects.
    result.effects = this.effects?.size > 0 ? this.effects.contents : [];

    return result;
  }

  async updateStress(resistance, value) {
    if (value > this.system.total_stress) {
      return await this.update({
        [`system.resistances.${resistance}.value`]:
          this.system.resistances[resistance].value + value,
      });
    }

    if (value <= 6) {
      return await this.update({
        [`system.resistances.${resistance}.value`]: 0,
        "system.pending_fallouts.minor": this.system.pending_fallouts.minor + 1,
      });
    } else {
      return await this.update({
        [`system.resistances.${resistance}.value`]: 0,
        "system.pending_fallouts.major": this.system.pending_fallouts.major + 1,
      });
    }
  }

  getActiveItems() {
    return this.items.reduce((out, item) => {
      out.push(...item.getActiveItems());
      return out;
    }, []);
  }
}
