name: Release
run-name: ${{ github.actor }} is creating release ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release this build as'
        required: true
        type: string
        default: 0.X.Y
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '>=23.9.0'
      - run: npm ci
      - run: npm run grammar
      - run: npm run build
      - run: npm run update-system -- 0.X.Y
      - name: Zip files
        run: zip -r ./heart.zip ./* -x node_modules -x src -x package*.json
      - name: Create Release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "./system.json,./heart.zip"
          tag: ${{ inputs.version }}